### ISSUE TITLE
Rename package to window-function

### ISSUE THREAD

**Issue by dy** [scijs/scijs-window-functions#5]
```js
var blackmanHarris = require('window-function/blackman-harris')
```
vs
```js
var blackmanHarris = require('scijs-window-functions/blackman-harris')
```
Isn't the first better? The second feels too proprietary or custom, although the package is pretty generic.

Prefixing packages with `scijs-` does not seem to be a pattern, even in that case namespace `@scijs/window-functions` would look like a better fit.

Still I suggest renaming package to just `window-function`, considering the name is free.

@rreusser what do you think?

**Comment by rreusser** [comment]
I like it. Changing.

**Comment by dy** [comment]
Yay

**Comment by rreusser** [comment]
There's always some loose ends when you switch this stuff, so let me know if anything jumps out, but I've made the change and deprecated the old! Thanks for pushing on cleanup/maintenance!

**Comment by dy** [comment]
@rreusser thanks, I appreciate! I can do maintenance too if you feel like not having time, just wanted to approve the change.

**Comment by rreusser** [comment]
No worries. I have the time. I usually just don't have the motivation because it feels like shouting into the void, but would love to take the good parts of scijs and tighten them up/present them a bit better. There's lots of useful stuff here, but lots of junk too, and the documentation/consistency was never really there. stdlib-js is obviously a good future to bet on since it's tackling scientific computing like the difficult problem that it is, but there's lots of low-hanging fruit here that could still be very useful.

**Comment by dy** [comment]
@rreusser ok if there is any sort of junk/abandonware feel free to drop it to [scrapjs](https://github.com/scrapjs)

**Comment by rreusser** [comment]
(Sorry if that was too negative. I appreciate all the feedback! Keep it coming and glad to clean up or help you do the same!)
